### ISSUE TITLE
L’URL de redirection n’a pas pu être trouvée

### ISSUE THREAD

**Issue by bachy** [YunoHost-Apps/mastodon_ynh#123]
Salut,
sur mon instance je n'arrive pas a suivre des comptes a distance, c'est a dire que je vais sur la home d'un compte sur une autre instance, je click sur suivre, le popup s'ouvre, j'entre mon adresse de profil et j'ai ce message d'erreur : L’URL de redirection n’a pas pu être trouvée

mastodon 2.5.2

```
yunohost --version
yunohost: 
  repo: stable
  version: 3.3.3
yunohost-admin: 
  repo: stable
  version: 3.3.1
moulinette: 
  repo: stable
  version: 3.3.1
ssowat: 
  repo: stable
  version: 3.3.2
```
une idée ?
