### ISSUE TITLE
Upgrade to 3.5.3~ynh2 failed

### ISSUE THREAD

**Issue by linuxissuper** [YunoHost-Apps/mastodon_ynh#332]
### Describe the bug
The upgrade actually worked but the services cannot start anymore

Upgrade log: https://linuxistsuper.de/privatebin/?a09868d1687f79fa#EzrtHb9DhqZ6vj4MEZai5SRoFwhN8A7vX99UaKewDVy7

journalctl for mastodon-web.service:   
https://linuxistsuper.de/privatebin/?87d6a220d6612dd4#93avbRCa1UYuSCj43QpvAZcJDYQugPLnPwmWsy1cGMVd

### Context

- Hardware: *VPS bought online *
- YunoHost version: 
```
yunohost:                              
  repo: stable                         
  version: 4.3.6.3                     
yunohost-admin:                        
  repo: testing                        
  version: 4.3.4.1                     
moulinette:                            
  repo: stable                         
  version: 4.3.3.1                     
ssowat:                                
  repo: stable                         
  version: 4.3.3.1                     
```
