### ISSUE TITLE
upgrade 4.2.3~ynh2 to 4.2.5~ynh1   is KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#435]
### Describe the bug

upgrade `4.2.3~ynh2` to `4.2.5~ynh1`   is KO

### Context
- server is a VPS
- YunoHost version:
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.9.1
yunohost-admin: 
  repo: stable
  version: 11.2.4
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- trying to install package version/branch: `YNH_APP_MANIFEST_VERSION: 4.2.5~ynh1`
- If upgrading, current package version: `YNH_APP_CURRENT_VERSION: 4.2.3~ynh2`

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    # yunohost app upgrade mastodon
    ```

### Logs
https://paste.yunohost.org/raw/ifaribarun

thx for your help , 
this upgrade is critical cf https://github.com/mastodon/mastodon/releases/tag/v4.2.5
